//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfApreciat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluareProfesorApreciat
    {
        public int ID_EvaluareProfesor { get; set; }
        public int ID_ProgramStudiu { get; set; }
        public int ID_Profesor { get; set; }
        public short NumarVoturi { get; set; }
    
        public virtual Profesor Profesor { get; set; }
        public virtual ProgramStudiu ProgramStudiu { get; set; }
    }
}
