//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfApreciat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDNNDatabaseEntities : DbContext
    {
        public MyDNNDatabaseEntities()
            : base("name=MyDNNDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<ProgramStudiu> ProgramStudius { get; set; }
        public virtual DbSet<RezultatVotProfesorProgramStudiu> RezultatVotProfesorProgramStudius { get; set; }
        public virtual DbSet<TipCicluInvatamant> TipCicluInvatamants { get; set; }
    
        public virtual int spAdaugaFacultate(string denumireScurta, string denumire, ObjectParameter responseMessage, ObjectParameter insertedID)
        {
            var denumireScurtaParameter = denumireScurta != null ?
                new ObjectParameter("denumireScurta", denumireScurta) :
                new ObjectParameter("denumireScurta", typeof(string));
    
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaFacultate", denumireScurtaParameter, denumireParameter, responseMessage, insertedID);
        }
    
        public virtual int spAdaugaProfesor(string nume, string prenume, string email, string gradDidactic, string facultateServiciu, Nullable<bool> eligibilRemunerare, ObjectParameter responseMessage, ObjectParameter insertedID)
        {
            var numeParameter = nume != null ?
                new ObjectParameter("nume", nume) :
                new ObjectParameter("nume", typeof(string));
    
            var prenumeParameter = prenume != null ?
                new ObjectParameter("prenume", prenume) :
                new ObjectParameter("prenume", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var gradDidacticParameter = gradDidactic != null ?
                new ObjectParameter("gradDidactic", gradDidactic) :
                new ObjectParameter("gradDidactic", typeof(string));
    
            var facultateServiciuParameter = facultateServiciu != null ?
                new ObjectParameter("FacultateServiciu", facultateServiciu) :
                new ObjectParameter("FacultateServiciu", typeof(string));
    
            var eligibilRemunerareParameter = eligibilRemunerare.HasValue ?
                new ObjectParameter("eligibilRemunerare", eligibilRemunerare) :
                new ObjectParameter("eligibilRemunerare", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaProfesor", numeParameter, prenumeParameter, emailParameter, gradDidacticParameter, facultateServiciuParameter, eligibilRemunerareParameter, responseMessage, insertedID);
        }
    
        public virtual int spAdaugaProgramStudiu(string facultate, Nullable<int> idTipCiclu, string denumireScurta, string denumire, Nullable<int> numarAbsolventi, Nullable<int> numarVotanti, ObjectParameter responseMessage, ObjectParameter insertedID)
        {
            var facultateParameter = facultate != null ?
                new ObjectParameter("Facultate", facultate) :
                new ObjectParameter("Facultate", typeof(string));
    
            var idTipCicluParameter = idTipCiclu.HasValue ?
                new ObjectParameter("idTipCiclu", idTipCiclu) :
                new ObjectParameter("idTipCiclu", typeof(int));
    
            var denumireScurtaParameter = denumireScurta != null ?
                new ObjectParameter("denumireScurta", denumireScurta) :
                new ObjectParameter("denumireScurta", typeof(string));
    
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            var numarAbsolventiParameter = numarAbsolventi.HasValue ?
                new ObjectParameter("numarAbsolventi", numarAbsolventi) :
                new ObjectParameter("numarAbsolventi", typeof(int));
    
            var numarVotantiParameter = numarVotanti.HasValue ?
                new ObjectParameter("numarVotanti", numarVotanti) :
                new ObjectParameter("numarVotanti", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaProgramStudiu", facultateParameter, idTipCicluParameter, denumireScurtaParameter, denumireParameter, numarAbsolventiParameter, numarVotantiParameter, responseMessage, insertedID);
        }
    
        public virtual int spAdaugaRezultatVotProfesorProgramStudiu(Nullable<int> idProgramStudiu, Nullable<int> idProfesor, Nullable<short> numarVoturi, ObjectParameter responseMessage, ObjectParameter insertedID)
        {
            var idProgramStudiuParameter = idProgramStudiu.HasValue ?
                new ObjectParameter("idProgramStudiu", idProgramStudiu) :
                new ObjectParameter("idProgramStudiu", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            var numarVoturiParameter = numarVoturi.HasValue ?
                new ObjectParameter("numarVoturi", numarVoturi) :
                new ObjectParameter("numarVoturi", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaRezultatVotProfesorProgramStudiu", idProgramStudiuParameter, idProfesorParameter, numarVoturiParameter, responseMessage, insertedID);
        }
    
        public virtual int spAdaugaTipCicluInvatamant(string denumire, ObjectParameter responseMessage, ObjectParameter insertedID)
        {
            var denumireParameter = denumire != null ?
                new ObjectParameter("denumire", denumire) :
                new ObjectParameter("denumire", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAdaugaTipCicluInvatamant", denumireParameter, responseMessage, insertedID);
        }
    
        public virtual int spClearDatabase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spClearDatabase");
        }
    }
}
