//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfApreciat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDNNDatabaseEntities : DbContext
    {
        public MyDNNDatabaseEntities()
            : base("name=MyDNNDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EvaluareProfesorApreciat> EvaluareProfesorApreciats { get; set; }
        public virtual DbSet<Facultate> Facultates { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<ProgramStudiu> ProgramStudius { get; set; }
        public virtual DbSet<TipCicluInvatamant> TipCicluInvatamants { get; set; }
    }
}
