//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfApreciat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramStudiu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramStudiu()
        {
            this.RezultatVotProfesorProgramStudius = new HashSet<RezultatVotProfesorProgramStudiu>();
        }
    
        public int ID_ProgramStudiu { get; set; }
        public int ID_Facultate { get; set; }
        public int ID_TipCiclu { get; set; }
        public string DenumireScurta { get; set; }
        public string Denumire { get; set; }
    
        public virtual Facultate Facultate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezultatVotProfesorProgramStudiu> RezultatVotProfesorProgramStudius { get; set; }
        public virtual TipCicluInvatamant TipCicluInvatamant { get; set; }
    }
}
